tests/api.test.js
  APIs Endpoints
    ✓ should retrieve all reviews (40 ms)
~/workspace/BD6.3_CW$ npm run test

> nodejs@1.0.0 test
> jest

✖ Should retrieve all reviews (2.26867ms)
  TypeError: Cannot read properties of undefined (reading 'address')
      at Test.serverAddress (/home/runner/workspace/node_modules/supertest/lib/test.js:46:22)
      at new Test (/home/runner/workspace/node_modules/supertest/lib/test.js:34:14)
      at Object.obj.<computed> [as get] (/home/runner/workspace/node_modules/supertest/index.js:43:18)
      at get (/home/runner/workspace/BD6.3_CW/tests/api.test.js:45:42)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.start (node:internal/test_runner/test:833:17)
      at startSubtestAfterBootstrap (node:internal/test_runner/harness:296:17)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)

✖ Should retrieve a specific review by ID (0.44808ms)
  TypeError: Cannot read properties of undefined (reading 'address')
      at Test.serverAddress (/home/runner/workspace/node_modules/supertest/lib/test.js:46:22)
      at new Test (/home/runner/workspace/node_modules/supertest/lib/test.js:34:14)
      at Object.obj.<computed> [as get] (/home/runner/workspace/node_modules/supertest/index.js:43:18)
      at get (/home/runner/workspace/BD6.3_CW/tests/api.test.js:54:42)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)
      at Test.postRun (node:internal/test_runner/test:1045:19)
      at Test.run (node:internal/test_runner/test:973:12)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at startSubtestAfterBootstrap (node:internal/test_runner/harness:296:3)

✖ Should return 404 for non-existing reciew (0.29913ms)
  TypeError: _index.getReviewById.mockResilvedValue is not a function
      at mockResilvedValue (/home/runner/workspace/BD6.3_CW/tests/api.test.js:60:19)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)
      at Test.postRun (node:internal/test_runner/test:1045:19)
      at Test.run (node:internal/test_runner/test:973:12)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:7)

✖ should add a new review (0.33086ms)
  TypeError: Cannot read properties of undefined (reading 'address')
      at Test.serverAddress (/home/runner/workspace/node_modules/supertest/lib/test.js:46:22)
      at new Test (/home/runner/workspace/node_modules/supertest/lib/test.js:34:14)
      at Object.obj.<computed> [as post] (/home/runner/workspace/node_modules/supertest/index.js:43:18)
      at post (/home/runner/workspace/BD6.3_CW/tests/api.test.js:71:8)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)
      at Test.postRun (node:internal/test_runner/test:1045:19)
      at Test.run (node:internal/test_runner/test:973:12)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:7)

 FAIL  tests/api.test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (../node_modules/@jest/core/build/TestScheduler.js:133:18)
      at ../node_modules/@jest/core/build/TestScheduler.js:254:19
      at ../node_modules/emittery/index.js:363:13
          at Array.map (<anonymous>)
      at Emittery.emit (../node_modules/emittery/index.js:361:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.29 s, estimated 2 s
Ran all test suites.
ℹ tests 4
ℹ suites 0
ℹ pass 0
ℹ fail 4
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 86.785513

✖ failing tests:

test at tests/api.test.js:46:20
✖ Should retrieve all reviews (2.26867ms)
  TypeError: Cannot read properties of undefined (reading 'address')
      at Test.serverAddress (/home/runner/workspace/node_modules/supertest/lib/test.js:46:22)
      at new Test (/home/runner/workspace/node_modules/supertest/lib/test.js:34:14)
      at Object.obj.<computed> [as get] (/home/runner/workspace/node_modules/supertest/index.js:43:18)
      at get (/home/runner/workspace/BD6.3_CW/tests/api.test.js:45:42)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.start (node:internal/test_runner/test:833:17)
      at startSubtestAfterBootstrap (node:internal/test_runner/harness:296:17)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)

test at tests/api.test.js:73:20
✖ Should retrieve a specific review by ID (0.44808ms)
  TypeError: Cannot read properties of undefined (reading 'address')
      at Test.serverAddress (/home/runner/workspace/node_modules/supertest/lib/test.js:46:22)
      at new Test (/home/runner/workspace/node_modules/supertest/lib/test.js:34:14)
      at Object.obj.<computed> [as get] (/home/runner/workspace/node_modules/supertest/index.js:43:18)
      at get (/home/runner/workspace/BD6.3_CW/tests/api.test.js:54:42)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)
      at Test.postRun (node:internal/test_runner/test:1045:19)
      at Test.run (node:internal/test_runner/test:973:12)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at startSubtestAfterBootstrap (node:internal/test_runner/harness:296:3)

test at tests/api.test.js:96:20
✖ Should return 404 for non-existing reciew (0.29913ms)
  TypeError: _index.getReviewById.mockResilvedValue is not a function
      at mockResilvedValue (/home/runner/workspace/BD6.3_CW/tests/api.test.js:60:19)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)
      at Test.postRun (node:internal/test_runner/test:1045:19)
      at Test.run (node:internal/test_runner/test:973:12)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:7)

test at tests/api.test.js:113:20
✖ should add a new review (0.33086ms)
  TypeError: Cannot read properties of undefined (reading 'address')
      at Test.serverAddress (/home/runner/workspace/node_modules/supertest/lib/test.js:46:22)
      at new Test (/home/runner/workspace/node_modules/supertest/lib/test.js:34:14)
      at Object.obj.<computed> [as post] (/home/runner/workspace/node_modules/supertest/index.js:43:18)
      at post (/home/runner/workspace/BD6.3_CW/tests/api.test.js:71:8)
      at call (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator.tryCatch (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Generator._invoke [as next] (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at asyncGeneratorStep (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at _next (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at new Promise (<anonymous>)
      at TestContext.<anonymous> (/home/runner/workspace/BD6.3_CW/tests/api.test.js:2:1)
      at Test.runInAsyncScope (node:async_hooks:211:14)
      at Test.run (node:internal/test_runner/test:934:25)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:18)
      at Test.postRun (node:internal/test_runner/test:1045:19)
      at Test.run (node:internal/test_runner/test:973:12)
      at processTicksAndRejections (node:internal/process/task_queues:105:5)
      at Test.processPendingSubtests (node:internal/test_runner/test:633:7)